### ISSUE TITLE
how to send config

### ISSUE THREAD

**Issue by trendzetter** [kadena-io/pact-lsp#7]
https://github.com/kadena-io/pact-lsp#server-configuration shows an example config but how do I pass it to the LSP ?
is there a default config file name?
I tried pasting it in the STDIN but no luck.

**Comment by rsoeldner** [comment]
You can send a configuration via the initialize request, see https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#initialize or via https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#workspace_didChangeConfiguration.
The details depend on your LSP client. What in particular do you need?
